### ISSUE TITLE
Dashboard cards are overlapping

### ISSUE THREAD

**Issue by alok-os** [Sunbird-cQube/cQube_Edu#105]
cards are overlapping if my browser is in 100% zoom. If 90% it works fine. Macbook mid-2012 model. see the image:

![image](https://user-images.githubusercontent.com/79843662/180602446-b1ff1d09-dc30-4d47-846a-cad58275f798.png)

**Comment by abhineetsingh10** [comment]
@alok-os - Can you please check if this issue is resolved as per your laptop and accordingly close the ticket.

**Comment by alok-os** [comment]
it is working fine now
