### ISSUE TITLE
Unknown value should be removed from the dropdown (NIPUN BHARAT)

### ISSUE THREAD

**Issue by TLSravani** [Sunbird-cQube/cQube_Edu#115]

**Comment by abhineetsingh10** [comment]
I spoke with Ikpreet and since the Subject is Unknown we cannot fix the issue at hand. We decided to keep the values but would request if the Unknow option is shown at the very end basis the alphabetical order.

**Comment by TLSravani** [comment]
"Unknown" value is presenting in the subject dropdown. I spoke with abhineet regarding this. He checked with Ikpreet and requested unknown option is shown at the very end basis. 
We implemented the same.
