### ISSUE TITLE
NISHTHA- Different metrics shown in District Wise Status vs Course Wise Status

### ISSUE THREAD

**Issue by abhineetsingh10** [Sunbird-cQube/cQube_Edu#179]
In the District Wise Status, we are showing data on Total Enrolments and Certifications whereas in Course Wise Status we are showing Total Enrolments and Completion. We need to ensure consistency across the two dashboards.

**Comment by TLSravani** [comment]
@abhineetsingh10 
Could you please mention which column needs to be integrate in both the visuals to make consistency?

**Comment by TLSravani** [comment]
@abhineetsingh10 
Could you please mention which column needs to be integrate in both the visuals to make consistency?

**Comment by abhineetsingh10** [comment]
@TLSravani - We need to use Enrollment and Certification for both the visuals.

**Comment by TLSravani** [comment]
ok. Thank you

**Comment by TLSravani** [comment]
Previously we showed total completion in course wise status visual. 
Now we integrated Certification column to make consistency in both state wise status and course wise status visuals - Taken Abhineet Inputs here. 
This Issue has been resolved.
