### ISSUE TITLE
Left pane (sidebar) behaviour

### ISSUE THREAD

**Issue by surendrasinghs** [Sunbird-cQube/cQube_Edu#21]
When open, it should push the page's content to the right and not overlay. When closed, it should expand the content of the page to fill. See the demo here https://www.w3schools.com/howto/howto_js_collapse_sidebar.asp

On the Home/Dashboard page the sidebar should be closed by default.

**Comment by abhineetsingh10** [comment]
@surendrasinghs - This is working so I am closing this ticket on your behalf.
