### ISSUE TITLE
Change the icon of (i) that tells more info about the program. 

### ISSUE THREAD

**Issue by Ikpreet-Singh** [Sunbird-cQube/cQube_Edu#22]
Below is the as is. 

<img width="254" alt="image" src="https://user-images.githubusercontent.com/19796202/179467262-0d1526dd-8811-4458-9d9f-7192dfa0ebe2.png">

you can use some like below : 
![image](https://user-images.githubusercontent.com/19796202/179473915-2c717440-6235-4461-b5cd-96ebb88fb7d3.png)

**Comment by surendrasinghs** [comment]
Please inspect the Figma file and take the icon specifications from there.
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/10580754/179474636-7c4accf2-7dd7-4a63-a246-086a7835b1ff.png">

**Comment by Ikpreet-Singh** [comment]
This looks better .. can we change the location of the same. Like bring it down somewhere or make it much more smaller and put it next to the program name. Eg shown below : 
<img width="222" alt="image" src="https://user-images.githubusercontent.com/19796202/179475672-800c0a83-a837-4b76-b6c8-be70e0996902.png">

**Comment by abhineetsingh10** [comment]
@Ikpreet-Singh - This has been incorporated so closing this ticket on your behalf.
