### ISSUE TITLE
Text size of Programs and VSK 

### ISSUE THREAD

**Issue by Ikpreet-Singh** [Sunbird-cQube/cQube_Edu#23]
Can the test size of programs and NVSK by increased and made more prominent. Please use design teams help to get some inputs.

**Comment by surendrasinghs** [comment]
Please refer to the design for font sizes of page title and program card https://www.figma.com/file/OzCfWWoTJPBkz1mqGpJ9Lv/cQube_2022?node-id=0%3A1 @TLSravani @pandutibil
