### ISSUE TITLE
Location of "i" icon on more info 

### ISSUE THREAD

**Issue by Ikpreet-Singh** [Sunbird-cQube/cQube_Edu#24]
Currently this looks like the first thing on the card and is very prominent. Can we reduce the size and change the location to towards the down side of the card. Design team can suggest ideas.

**Comment by surendrasinghs** [comment]
One option is to have at the end of the Name of the program (text). See the info icon next to "Date Range" in https://i.stack.imgur.com/zmSYK.png and

**Comment by abhineetsingh10** [comment]
@Ikpreet-Singh - This has been incorporated in NVSK so closing this on your behalf.
