### ISSUE TITLE
NISHTHA (NVSK) - Course Wise Status - Bar Graph Value

### ISSUE THREAD

**Issue by TLSravani** [Sunbird-cQube/cQube_Edu#249]
Bar is presenting if value is '0' as well.

**Comment by abhineetsingh10** [comment]
Can you please outline the instance when this is happening so that I can test it and validate the fix.

**Comment by TLSravani** [comment]
Here the bar is presenting if value is zero as well. Now the issue is resolved. Please find the below screenshot


![Image](https://user-images.githubusercontent.com/108678048/186859293-8a413c4c-3d03-4dce-a050-d912c2af978c.png)
