### ISSUE TITLE
<URGENT> confusing representation 

### ISSUE THREAD

**Issue by Ikpreet-Singh** [Sunbird-cQube/cQube_Edu#26]
<img width="370" alt="image" src="https://user-images.githubusercontent.com/19796202/179527701-e64780e4-ddc1-41df-b334-a1cf14902d6e.png">

Dr. Behera got confused on the above visualizations and was not able to understand the graph. 
Can we : 
1. Show that the bar represents 100% and dark part is the completed data. 
2. Apart from showcasing numbers in percentages, we need to show absolute numbers. Eg: The full bar represents 200000 teachers and dark part is 150000 teachers . And apart from these 2 absolute number, please show that overall enrollment is 75%. 
3. Please DO NOT show the break in the bars.. it should look like a bar is getting filled. Somehting like in the image below : 
<img width="395" alt="image" src="https://user-images.githubusercontent.com/19796202/179529528-f7f1e0ca-ba9c-4379-8b02-b29ecd28a3c7.png">

@surendrasinghs @abhineet

**Comment by abhineetsingh10** [comment]
@Ikpreet-Singh - This issue is fixed in NVSK but the current light blue colour isn't very visible at the NVSK centre at NCERT. I am closing this ticket but will raise a new ticket to highlight the issue of the light blue colour.
