### ISSUE TITLE
Scatterplot Chart correlating data across programs

### ISSUE THREAD

**Issue by TLSravani** [Sunbird-cQube/cQube_Edu#39]

**Comment by abhineetsingh10** [comment]
@TLSravani - This hasn't been created so we need to move this out of the 'Ready for UAT' label. 
@surendrasinghs - We need to enable this for future use cases.

**Comment by surendrasinghs** [comment]
Updated issue for roadmap. Related discussion with more details https://github.com/orgs/Sunbird-cQube/discussions/70
