### ISSUE TITLE
Key and Vanity Metrics Data Points

### ISSUE THREAD

**Issue by abhineetsingh10** [Sunbird-cQube/cQube_Edu#4]
Request you to refer to the following sheet (Sheet #2) to get inputs on Key Metrics and Vanity metrics for NVSK.

https://docs.google.com/spreadsheets/d/1p4wCBruUge7y8-8z3aKHRyo82jQC_eUALD63HO9tH7s/edit#gid=0

**Comment by TLSravani** [comment]
Issue got fixed
