### ISSUE TITLE
Incorrect spelling for Nishtha and issues with options in the dropdown

### ISSUE THREAD

**Issue by abhineetsingh10** [Sunbird-cQube/cQube_Edu#5]
Incorrect spelling of Nishtha used in the dropdown. Also, I am observing two options for each Nishtha program. See the image below.

![Screenshot 2022-07-14 at 1 11 22 PM](https://user-images.githubusercontent.com/42932758/179155429-55038f88-8078-4ac9-a416-79474fc990d1.png)

**Comment by TLSravani** [comment]
Issue has been resolved. Please find the below screenshot.
![Nishtha Spelling](https://user-images.githubusercontent.com/108678048/179344844-44c22368-8ac8-437f-b027-0469636f1b84.PNG)
