### ISSUE TITLE
India map with states should be changed to filled map (Either Yes/No or 4 Color Gradients with blue color)

### ISSUE THREAD

**Issue by TLSravani** [Sunbird-cQube/cQube_Edu#54]

**Comment by abhineetsingh10** [comment]
In the case of Yes or No, we need you to use the following colours-
Yes- 33,113,181
No- 239,243,255

In the case of four gradients, we need to use the following colours-
Lowest-> 
239,243,255
189,215,231
107,174,214
33,113,181
<-Highest

**Comment by TLSravani** [comment]
Duplicate Issue Created
