### ISSUE TITLE
List of dashboards where India Map with states should be changed to filled map. Adding colour for team's reference.

### ISSUE THREAD

**Issue by abhineetsingh10** [Sunbird-cQube/cQube_Edu#59]
Desired Output

![Image](https://user-images.githubusercontent.com/42932758/180134121-fa9d4499-2c31-4f89-8933-382ad20ed4c5.png)

List of Dashboards where this visual is required- 

NISHTHA- Program Status
ETB & E-content- ETB Program
PM POSHAN- States Onboarded
Micro Improvement Program- Micro Improvement Program

Colour Information
Yes- 33,113,181
No- 239,243,255

**Comment by TLSravani** [comment]
Changed to filled map and updated the colors which are provided.
