### ISSUE TITLE
Please change the column names and sort by Total Courses

### ISSUE THREAD

**Issue by abhineetsingh10** [Sunbird-cQube/cQube_Edu#60]
NISHTHA- Total Courses and Medium

Please change the name of the columns as highlighted in the image below. 

Need to sort the data in Descending order by Total Courses. 

![Image](https://user-images.githubusercontent.com/42932758/180139588-337c99fb-5465-459d-9a7c-7daa7c969bd4.png)

**Comment by abhineetsingh10** [comment]
@TLSravani - While we have sorted the column basis Courses launched, the name of the columns is still unchanged. Please change the column names to 'Total Courses Launched' and 'Total Mediums'.

**Comment by TLSravani** [comment]
Issue has been resolved before whatever the ticket says. But, again we were asked to change the column names to count of courses launched and count of course mediums in the time of demo.
