### ISSUE TITLE
Logo for Dashboard not loading

### ISSUE THREAD

**Issue by abhineetsingh10** [Sunbird-cQube/cQube_Edu#7]
![Screenshot 2022-07-15 at 10 48 03 AM](https://user-images.githubusercontent.com/42932758/179155834-0a531cc9-d3de-4f62-b0bd-425c0805e4f5.png)

**Comment by TLSravani** [comment]
Issue has been resolved. Please find the below screenshot.

![Dashboard Logo](https://user-images.githubusercontent.com/108678048/179342209-37b3218a-567f-4f7f-a0dd-a82ea99dca04.PNG)
