### ISSUE TITLE
Change UDISE to UDISE+

### ISSUE THREAD

**Issue by abhineetsingh10** [Sunbird-cQube/cQube_Edu#76]
Please change UDISE to UDISE+

![Image](https://user-images.githubusercontent.com/42932758/180173344-b041198f-78c1-4c19-8d62-29fd406c0cce.png)

![Image](https://user-images.githubusercontent.com/42932758/180173543-55562720-5390-4160-813f-54dfa5c1a149.png)

**Comment by pramodkvarma** [comment]
@SreenivasNimmagadda @surendrasinghs please ensure we use generic labels in software for these (NOT UDISE etc) and have the NVSK implementation configure it.
