### ISSUE TITLE
Multiple filters should work independently 

### ISSUE THREAD

**Issue by Ikpreet-Singh** [Sunbird-cQube/cQube_Edu#80]
Apart from ETB medium, grade subject filter, the filters shown in the image below should work independently too. 

<img width="743" alt="image" src="https://user-images.githubusercontent.com/19796202/180250842-c73f3401-cb66-4a3e-a320-d2d4f35de544.png">

**Comment by abhineetsingh10** [comment]
@TLSravani - Need to review this with you.

**Comment by TLSravani** [comment]
Issue has been resolved
