### ISSUE TITLE
Tab names and sequencing to be corrected. 

### ISSUE THREAD

**Issue by Ikpreet-Singh** [Sunbird-cQube/cQube_Edu#81]
PS the link below and correct the program, tab names and program sequencing as per the sheet.

[https://docs.google.com/spreadsheets/d/1uKLCnFu36P09NOL0qGgIiQABqUFnVabOKwjsUlEEzww/edit#gid=0](url)

Column A will suggest the sequencing of the Programs to be seen on Dashboard
Column B will suggest the Program name and Spelling and casing (UPPER case or lower case)
Column C is having the old tab name that comes after clicking the Program Card-Access Dashboard (just for reference)
Column D will provide the new tab name for Column C names. 
Column E will show the sequence of the tabs. 

IMPORTANT : PLEASE START WITH THE ONES MARKED IN GREEN

@surendrasinghs can you pls help tagging with Projects.

**Comment by abhineetsingh10** [comment]
@Ikpreet-Singh - This has been incorporated so closing on your behalf.
