### ISSUE TITLE
SHOW FILTERS FOR ALL 3 NISHTHA 

### ISSUE THREAD

**Issue by Ikpreet-Singh** [Sunbird-cQube/cQube_Edu#83]
<img width="656" alt="image" src="https://user-images.githubusercontent.com/19796202/180365218-e259db46-c693-4f14-b844-24b6d395b827.png">

Please make sure that these filters are consistent across the board.

**Comment by TLSravani** [comment]
@Ikpreet-Singh 
As data is having only for NISHTHA 3.0, we can see only NISHTHA 3.0.

**Comment by Ikpreet-Singh** [comment]
@abhineetsingh10 can you help here pls.

**Comment by abhineetsingh10** [comment]
@Ikpreet-Singh - This is done. Closing on your behalf.
