### ISSUE TITLE
Adding footer in the website 

### ISSUE THREAD

**Issue by Ikpreet-Singh** [Sunbird-cQube/cQube_Edu#84]
Please refer to the the image below and a similar footer should be added in the cQube website. 

<img width="312" alt="image" src="https://user-images.githubusercontent.com/19796202/180375298-d30fe69d-1d4f-4517-9698-3ad3e2cc892a.png">

PFA the logo for NIC 

![nic (2)](https://user-images.githubusercontent.com/19796202/180375465-fc780ea1-667c-4633-abcd-4440e1d058cf.png)

Below this logo, please add the sentence the sentence written below : 

Copyright © 2021 National Information Centre All Rights Reserved

**Comment by abhineetsingh10** [comment]
@Ikpreet-Singh - This has been incorporated so closing on your behalf. The team has made 2021 to 2022 so I am assuming no change is required on that.
