### ISSUE TITLE
Adding footer in the website

### ISSUE THREAD

**Issue by TLSravani** [Sunbird-cQube/cQube_Edu#85]
Please refer to the the image below and a similar footer should be added in the cQube website.

![Image](https://user-images.githubusercontent.com/108678048/180388054-44fc0fa1-f668-45cf-8a8c-f3fa6133c0e1.png)

PFA the logo for NIC

nic (2)

Below this logo, please add the sentence the sentence written below :

Copyright © 2021 National Information Centre All Rights Reserved

**Comment by surendrasinghs** [comment]
Use this logo https://xn--m1bet4hqd2b.xn--h2brj9c/wp-content/themes/NICTheme/assets/images/logo.png
Add this text below "Copyright © 2021 National Information Centre All Rights Reserved"

See preview above in the initial comment.
