### ISSUE TITLE
Tab names and sequencing to be corrected.

### ISSUE THREAD

**Issue by TLSravani** [Sunbird-cQube/cQube_Edu#86]

**Comment by TLSravani** [comment]
PS the link below and correct the program, tab names and program sequencing as per the sheet.

[https://docs.google.com/spreadsheets/d/1uKLCnFu36P09NOL0qGgIiQABqUFnVabOKwjsUlEEzww/edit#gid=0](https://github.com/Sunbird-cQube/cQube_Edu/issues/url)

Column A will suggest the sequencing of the Programs to be seen on Dashboard
Column B will suggest the Program name and Spelling and casing (UPPER case or lower case)
Column C is having the old tab name that comes after clicking the Program Card-Access Dashboard (just for reference)
Column D will provide the new tab name for Column C names.
Column E will show the sequence of the tabs.

IMPORTANT : PLEASE START WITH THE ONES MARKED IN GREEN

@surendrasinghs can you pls help tagging with Projects.

**Comment by Ikpreet-Singh** [comment]
All the rows have been updated. Please configure.

**Comment by TLSravani** [comment]
Duplicated Record Created
