### ISSUE TITLE
Deleting a tab from NIPUN Bharat 

### ISSUE THREAD

**Issue by Ikpreet-Singh** [Sunbird-cQube/cQube_Edu#89]
Please delete the tab **"content wise consumption/resources"** from NIPUN Bharat. We dont want to show this data. 

<img width="723" alt="image" src="https://user-images.githubusercontent.com/19796202/180492837-7b303ccd-787f-467d-8308-780da3629dfd.png">

**Comment by abhineetsingh10** [comment]
@Ikpreet-Singh - This has been incorporated so closing on your behalf.
