### ISSUE TITLE
Issues with Tooltip

### ISSUE THREAD

**Issue by abhineetsingh10** [Sunbird-cQube/cQube_Edu#9]
The tooltip needs proper formatting. Also, it shows information about ETB for some odd reason. 

The following tooltip should be here-
------------
State Name- Punjab
Participation in Nishtha 1.0- Yes
Participation in Nishtha 2.0- Yes
Participation in Nishtha 3.0- No
------------

![Screenshot 2022-07-15 at 10 53 35 AM](https://user-images.githubusercontent.com/42932758/179156476-f08108c5-86cb-41da-9804-dd4f417eaa65.png)

**Comment by TLSravani** [comment]
Issue got resolved
