### ISSUE TITLE
ETB data tool tip changes 

### ISSUE THREAD

**Issue by Ikpreet-Singh** [Sunbird-cQube/cQube_Edu#90]
The tool tip that comes on top of a state should only say 
Textbooks Energised : **Yes**

Same for the Legend Value

Eg: 
Textbooks Energized : **Yes** 

![image](https://user-images.githubusercontent.com/19796202/180493221-12d31267-1460-499f-bf44-278a9002e383.png)

**Comment by abhineetsingh10** [comment]
@Ikpreet-Singh- This has been incorporated so closing on your behalf.
