### ISSUE TITLE
Font should be smaller and italics for ETB : Energized Textbooks

### ISSUE THREAD

**Issue by Ikpreet-Singh** [Sunbird-cQube/cQube_Edu#92]
Font should be 4-5 size smaller and italics for ETB : Energized Textbooks in the image below : 
Change to Italic only in the bracket text

<img width="611" alt="image" src="https://user-images.githubusercontent.com/19796202/180494654-82551bbd-ceea-4f90-9247-9d9871ee81b9.png">

**Comment by abhineetsingh10** [comment]
@Ikpreet-Singh- This is done so closing on your behalf.
